# Generated by Django 5.1.3 on 2024-11-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikhil', '0002_hotels_description_alter_rooms_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='description',
            field=models.CharField(default='', max_length=500000),
        ),
    ]
