# Generated by Django 5.1.3 on 2024-11-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikhil', '0003_alter_hotels_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/'),
        ),
    ]
