# Generated by Django 5.1.3 on 2024-11-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikhil', '0004_hotels_image_1_hotels_image_2_hotels_image_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/'),
        ),
    ]
