# Generated by Django 5.1.3 on 2024-11-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikhil', '0005_alter_hotels_image_1_alter_hotels_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
